# Generated by Django 2.2.5 on 2019-11-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='define_post_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
                ('label_structure', models.CharField(choices=[('AU', 'Audio'), ('TX', 'Text'), ('IM', 'Image'), ('INT', 'Integer'), ('DATE', 'Date'), ('VIDEO', 'Vide'), ('EM', 'E-mail'), ('LOC', 'Location'), ('URL', 'URL')], default='TX', max_length=10)),
                ('label_isrequired', models.BooleanField(default=False)),
            ],
        ),
    ]
