# Generated by Django 2.2.5 on 2019-11-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_define_post_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='define_post_types',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community_header'),
        ),
        migrations.AddField(
            model_name='post_type_header',
            name='fields',
            field=models.ManyToManyField(to='community.define_post_types'),
        ),
        migrations.AlterField(
            model_name='post_type_header',
            name='post_community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community_header'),
        ),
    ]
