# Generated by Django 2.2.5 on 2019-11-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191123_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='define_post_types',
            name='community',
        ),
    ]
