# Generated by Django 2.2.5 on 2019-11-24 15:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_define_post_types_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_type_header',
            name='fields_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
