# Generated by Django 2.2.5 on 2019-11-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_type_header_fields_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='define_post_types',
            name='post_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community_header'),
        ),
    ]
