# Generated by Django 2.2.5 on 2019-11-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_define_post_types_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_type_header',
            name='fields_type',
        ),
    ]
