# Generated by Django 2.2.5 on 2019-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_post_type_header_fields_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_header',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
