# Generated by Django 2.2.5 on 2019-12-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_type_header',
            old_name='fields',
            new_name='datafields',
        ),
    ]
