# Generated by Django 2.2.5 on 2019-12-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20191211_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_header',
            old_name='user_name',
            new_name='user',
        ),
    ]
