# Generated by Django 2.2.5 on 2019-12-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_community_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_join',
            old_name='community',
            new_name='related_community',
        ),
    ]
