# Generated by Django 2.2.5 on 2019-12-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_post_type_header_post_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_type_header',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
