# Generated by Django 2.2.5 on 2019-12-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_auto_20191221_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_header',
            name='wikidata',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
