# Generated by Django 2.2.5 on 2019-12-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_community_header_wikidata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community_header',
            name='wikidata',
        ),
    ]
